# Site settings
title: Brian Ambielli
email: brian.ambielli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome! I'm a Software Developer with a focus on Software Quality,
  working at Syndio in Chicago, IL. I write, test, and ship high quality code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.bambielli.com" # the base hostname & protocol for your site
github_username:  bambielli

# Build settings
markdown: kramdown
